# general settings #####################################################################################################
name: c_v3_JinchenSRN
model_type: IRModel
num_gpu: 1  # 0 for cpu mode
manual_seed: 42
bit: 8 # data type



# network structures ###################################################################################################
network_g:
  type: JinchenSRN
  dim: 180
  n_groups: 8
  n_blocks: 6
  num_heads: 3
  mlp_ratio: 2
  num_sa: 2
  window_list:  [ [32, 8],[8, 32], [32, 8],[8, 32], [32, 8],[8, 32] ]
  shift_list:   [ [16, 4],[4, 16], [16, 4],[4, 16], [16, 4],[4, 16] ]


# path #################################################################################################################
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings ####################################################################################################
train:
  # basic setting
  gt_size: 256
  batch_size_per_gpu: 8
  total_iter: 1000000

  # optimizer setting
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [ 0.9, 0.999 ]

 # scheduler setting
  scheduler:
    type: CosineAnnealingRestartLR
    periods: [ 1000000 ]
    restart_weights: [ 1 ]
    eta_min: !!float 1e-6

#  scheduler:
#    type: MultiStepLR
#    milestones: [ 200000, 400000, 600000, 800000 ]
#    gamma: 0.5

  # loss setting
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


# validation settings ##################################################################################################
val:
  val_freq: 1000
  save_img: false
  suffix: ~

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true